
namespace: batel-ns

deployment:
  name: batel-app
  replicas: 1
  image:
    repository: 314525640319.dkr.ecr.us-east-2.amazonaws.com/batel-app-img
    tag: v0.1.1
  command:
    - node
    - index.js
  containerPort: 3000
  secrets:
    name: db-secret

service:
  name: batel-app-service
  type: NodePort
  port: 3000
  targetPort: 3000
  