apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.awsSecretName }}
        property: host
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.awsSecretName }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.awsSecretName }}
        property: password
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.awsSecretName }}
        property: dbInstanceIdentifier
